import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/products',
          '/categories',
          '/category/*',
          '/search',
          '/about',
          '/contact',
          '/delivery',
          '/services',
          '/privacy',
          '/terms',
        ],
        disallow: [
          '/admin/',
          '/api/',
          '/dashboard/',
          '/profile/',
          '/cart/',
          '/wishlist/',
          '/checkout/',
          '/payment/',
          '/login/',
          '/register/',
          '/forgot-password/',
          '/reset-password/',
          '/unified-login/',
          '/offline/',
          '/_next/',
          '/static/',
          '*.json',
          '*.xml',
          '/uploads/',
        ],
        crawlDelay: 1,
      },
      {
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/products',
          '/categories',
          '/category/*',
          '/search',
          '/about',
          '/contact',
          '/delivery',
          '/services',
        ],
        disallow: [
          '/admin/',
          '/api/',
          '/dashboard/',
          '/profile/',
          '/cart/',
          '/wishlist/',
          '/checkout/',
          '/payment/',
          '/login/',
          '/register/',
        ],
        crawlDelay: 0,
      },
      {
        userAgent: 'Bingbot',
        allow: [
          '/',
          '/products',
          '/categories',
          '/category/*',
          '/search',
          '/about',
          '/contact',
          '/delivery',
          '/services',
        ],
        disallow: [
          '/admin/',
          '/api/',
          '/dashboard/',
          '/profile/',
          '/cart/',
          '/wishlist/',
          '/checkout/',
          '/payment/',
          '/login/',
          '/register/',
        ],
        crawlDelay: 1,
      },
    ],
    sitemap: 'https://akazubaflorist.com/sitemap.xml',
    host: 'https://akazubaflorist.com',
  }
}
